spectaql:
  targetDir: public/graphql
introspection:
  schemaFile: schema.graphql
servers:
  # NOTE: If not using introspection.url OR servers[], you need to provide x-url

  # same format as for OpenAPI Specification https://swagger.io/specification/#server-object

  - url: http://localhost:7070/graphql
    description: Local development gateway
    # Indicates to use this server's URL as the typical GraphQL request base in the documentation
    # If no server entries have this indicator, the first server's URL will be used.
    # If no server entries are defined at all, the Introspection URL will be used.
    production: true
    # A place to list any Headers for your GraphQL API calls
    headers:
      - name: Authorization
        example: Bearer <YOUR_TOKEN_HERE>
        comment: Your API token from the auth `/token` endpoint
info:
  title: GraphQL API Reference
  description: >
    Welcome to the OpenCRVS GraphQL API reference! This is an exhaustive list of all available endpoints and their respective schemas.

    <p>Learn how to authenticate to the API in the Getting started -guide: <a href="https://todo-todo.opencrvs.org">https://todo-todo.opencrvs.org</a></p>
    <p>FHIR-endpoint documentation: <a href="https://todo-todo.opencrvs.org">https://todo-todo.opencrvs.org</a></p>
